version: "3.7"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
  frontend:
    driver: ${NETWORKS_DRIVER}

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
    volumes: 
      - ./flask:/app
    expose:
      - 8080
    networks:
      - frontend
      - backend
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - flask
    networks:
      - frontend
      - backend

  postgres:
    build: ./postgres
    image: postgres:10
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend

